//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {


    public struct commonStrings {

        /// Base translation: Rename
        public static var rename : String = NSLocalizedString("commonStrings.rename", comment: "")

        /// Base translation: Cancel
        public static var cancel : String = NSLocalizedString("commonStrings.cancel", comment: "")

        /// Base translation: Send
        public static var send : String = NSLocalizedString("commonStrings.send", comment: "")

        /// Base translation: Delete
        public static var delete : String = NSLocalizedString("commonStrings.delete", comment: "")

        /// Base translation: Ok
        public static var ok : String = NSLocalizedString("commonStrings.ok", comment: "")

        /// Base translation: Open settings
        public static var openSettings : String = NSLocalizedString("commonStrings.openSettings", comment: "")

        /// Base translation: Back
        public static var back : String = NSLocalizedString("commonStrings.back", comment: "")

        /// Base translation: Yes
        public static var yes : String = NSLocalizedString("commonStrings.yes", comment: "")

        /// Base translation: No
        public static var no : String = NSLocalizedString("commonStrings.no", comment: "")

    }

    public struct navbar {


        public struct title {

            /// Base translation: Settings
            public static var settings : String = NSLocalizedString("navbar.title.settings", comment: "")

            /// Base translation: Learning
            public static var learning : String = NSLocalizedString("navbar.title.learning", comment: "")

            /// Base translation: Statistics
            public static var statistics : String = NSLocalizedString("navbar.title.statistics", comment: "")

        }
    }

    public struct settings {


        public struct createSet {

            /// Base translation: Add Word
            public static var addWord : String = NSLocalizedString("settings.createSet.addWord", comment: "")

            /// Base translation: Your Language
            public static var yourLanguage : String = NSLocalizedString("settings.createSet.yourLanguage", comment: "")

            /// Base translation: Learning Language
            public static var learningLanguage : String = NSLocalizedString("settings.createSet.learningLanguage", comment: "")

            /// Base translation: Set Name
            public static var setName : String = NSLocalizedString("settings.createSet.setName", comment: "")

            /// Base translation: Save
            public static var save : String = NSLocalizedString("settings.createSet.save", comment: "")

        }

        public struct selectLanguageSet {


            public struct navbar {

                /// Base translation: Select Your Known Language
                public static var selectYourKnownLanguage : String = NSLocalizedString("settings.selectLanguageSet.navbar.selectYourKnownLanguage", comment: "")

                /// Base translation: Select Your Learning Language
                public static var selectYourLearningLanguage : String = NSLocalizedString("settings.selectLanguageSet.navbar.selectYourLearningLanguage", comment: "")

            }
        }
    }
}